/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adega.telas;

import com.adega.dao.RefeicaoDao;
import com.adega.dao.VinhoDao;
import com.adega.modelo.Refeicao;
import com.adega.modelo.Vinho;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class Tela_Alterar_Refeicao extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Alterar_Refeição
     */
    public Tela_Alterar_Refeicao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        refeicao_Nome = new javax.swing.JTextField();
        refeicao_Vinho = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        refeicao_Descricao = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        verifaca_Refeicao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Salvar");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Vinho:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Descrição:");

        refeicao_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refeicao_NomeActionPerformed(evt);
            }
        });

        refeicao_Vinho.setEditable(false);
        refeicao_Vinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refeicao_VinhoActionPerformed(evt);
            }
        });

        refeicao_Descricao.setEditable(false);
        refeicao_Descricao.setColumns(20);
        refeicao_Descricao.setRows(5);
        jScrollPane1.setViewportView(refeicao_Descricao);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Alterar Refeição");

        verifaca_Refeicao.setText("Verificar");
        verifaca_Refeicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifaca_RefeicaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refeicao_Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verifaca_Refeicao, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(refeicao_Vinho)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(refeicao_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verifaca_Refeicao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refeicao_Vinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refeicao_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refeicao_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refeicao_NomeActionPerformed

    private void refeicao_VinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refeicao_VinhoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_refeicao_VinhoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(refeicao_Vinho.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null,"Campo Vinho em branco!");
            return;
        }
        if(refeicao_Descricao.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null,"Campo Descrição em branco!");
            return;
        }
        
        VinhoDao auxx = new VinhoDao();
        List<Vinho> vinhos = new ArrayList<>();
                      
        vinhos = auxx.getVinhos();
        
        for (Vinho vin : vinhos) {
            //System.out.println(vin.getNome());
            if(vin.getNome().equals(refeicao_Vinho.getText()))
            {
                
                RefeicaoDao refeicao = new RefeicaoDao();
                Refeicao ref = new Refeicao(refeicao_Nome.getText(), refeicao_Descricao.getText(), refeicao_Vinho.getText());
        
                refeicao.alteraRefeicao(ref);
        
                JOptionPane.showMessageDialog(null,"Refeição alterada com sucesso!");
        
                dispose(); 
                Tela_Gerenciar_Vinho_Refeição a = new Tela_Gerenciar_Vinho_Refeição();
                a.setVisible(true);
                
            }
        }
        
        
        
        //alterar dados no banco se OK...
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose(); 
        Tela_Gerenciar_Vinho_Refeição a = new Tela_Gerenciar_Vinho_Refeição();
        a.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void verifaca_RefeicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifaca_RefeicaoActionPerformed
        // verifica se refeiçao esta cadastrada
        if(refeicao_Nome.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null,"Campo Nome em branco!");
            return;
        }
        RefeicaoDao aux = new RefeicaoDao();
        List<Refeicao> refeicoes = new ArrayList<>();
                      
        refeicoes = aux.getRefeicoes();
        
        for (Refeicao ref : refeicoes) {
            
            if(ref.getNome().equals(refeicao_Nome.getText()))
            {
                refeicao_Vinho.setText(ref.getNome_Vinho());
                refeicao_Descricao.setText(ref.getDescricao());
                jButton1.setEnabled(true);
                refeicao_Nome.setEditable(false);
                
                refeicao_Descricao.setEditable(true);
                refeicao_Vinho.setEditable(true);
                
                return;
            }
        }
        
        JOptionPane.showMessageDialog(null,"Refeição não cadastrada!");
        
        
        
    }//GEN-LAST:event_verifaca_RefeicaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Alterar_Refeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Alterar_Refeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Alterar_Refeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Alterar_Refeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Alterar_Refeicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea refeicao_Descricao;
    private javax.swing.JTextField refeicao_Nome;
    private javax.swing.JTextField refeicao_Vinho;
    private javax.swing.JButton verifaca_Refeicao;
    // End of variables declaration//GEN-END:variables
}
