/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adega.telas;

import com.adega.modelo.Refeicao;
import com.adega.dao.RefeicaoDao;
import com.adega.dao.VinhoDao;
import com.adega.modelo.Vinho;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author 141965
 */
public class Tela_Adicionar_Refeicao extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Gerenciar_Refeição
     */
    public Tela_Adicionar_Refeicao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        refeicao_nome = new javax.swing.JTextField();
        refeicao_Vinho = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        refeicao_Descricao = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        Adicionar_refeicao = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Vinho:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Descrição:");

        refeicao_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refeicao_nomeActionPerformed(evt);
            }
        });

        refeicao_Vinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refeicao_VinhoActionPerformed(evt);
            }
        });

        refeicao_Descricao.setColumns(20);
        refeicao_Descricao.setRows(5);
        jScrollPane1.setViewportView(refeicao_Descricao);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Adicionar Refeição");

        Adicionar_refeicao.setText("Salvar");
        Adicionar_refeicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adicionar_refeicaoActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Adicionar_refeicao, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                    .addComponent(refeicao_nome)
                    .addComponent(refeicao_Vinho)
                    .addComponent(jScrollPane1))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(refeicao_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(refeicao_Vinho, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Adicionar_refeicao, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refeicao_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refeicao_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refeicao_nomeActionPerformed

    private void refeicao_VinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refeicao_VinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refeicao_VinhoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Tela_Gerenciar_Vinho_Refeição a = new Tela_Gerenciar_Vinho_Refeição();
        a.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Adicionar_refeicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adicionar_refeicaoActionPerformed
        
        
        if(refeicao_nome.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null,"Campo Nome em branco!");
            return;
        }if(refeicao_Vinho.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null,"Campo Vinho em branco!");
            return;
        }
        if(refeicao_Descricao.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null,"Campo Descrição em branco!");
            return;
        }
        
                  
        Refeicao refeicao = new Refeicao(refeicao_nome.getText(),refeicao_Descricao.getText() , refeicao_Vinho.getText());
        
        RefeicaoDao aux = new RefeicaoDao();
        List<Refeicao> refeicoes = new ArrayList<>();
                      
        refeicoes = aux.getRefeicoes();
        
        for (Refeicao ref : refeicoes) {
            
            if(ref.getNome().equals(refeicao_nome.getText()))
            {
                JOptionPane.showMessageDialog(null,"Refeição já cadastrada!");
                return;
            }
        }
        
        VinhoDao auxx = new VinhoDao();
        List<Vinho> vinhos = new ArrayList<>();
                      
        vinhos = auxx.getVinhos();
        
        for (Vinho vin : vinhos) {
            //System.out.println(vin.getNome());
            if(vin.getNome().equals(refeicao_Vinho.getText()))
            {
                
                RefeicaoDao  ref = new RefeicaoDao();
                ref.adicionaRefeicao(refeicao);//Salva informacoes dos campos no banco
                
                JOptionPane.showMessageDialog(null,"Refeição cadastrada com sucesso!");
                
                dispose();
                Tela_Gerenciar_Vinho_Refeição a = new Tela_Gerenciar_Vinho_Refeição();
                a.setVisible(true);
                return;
                
            }
        }
        
        JOptionPane.showMessageDialog(null,"Vinho deve ser cadastrado antes de atribuir a uma refeição!");
        
        
      
    
                
    }//GEN-LAST:event_Adicionar_refeicaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Adicionar_Refeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Adicionar_Refeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Adicionar_Refeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Adicionar_Refeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Adicionar_Refeicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adicionar_refeicao;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea refeicao_Descricao;
    private javax.swing.JTextField refeicao_Vinho;
    private javax.swing.JTextField refeicao_nome;
    // End of variables declaration//GEN-END:variables
}
