/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adega.telas;

import com.adega.dao.RefeicaoDao;
import com.adega.dao.VinhoDao;
import com.adega.modelo.Vinho;
import com.adega.telas.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author 141965
 */
public class Tela_Adicionar_Vinho extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Gerenciar_Refeição
     */
    public Tela_Adicionar_Vinho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vinho_Nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        adicionar_Vinho = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        vinho_Fabricante = new javax.swing.JTextField();
        vinho_Ano = new javax.swing.JTextField();
        vinho_Acucarado = new javax.swing.JTextField();
        vinho_Aroma = new javax.swing.JTextField();
        vinho_Preco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");

        vinho_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vinho_NomeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Adicionar Vinho");

        adicionar_Vinho.setText("Salvar");
        adicionar_Vinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionar_VinhoActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fabricante:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Açucarado:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ano:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Aroma:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Preço:");

        vinho_Fabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vinho_FabricanteActionPerformed(evt);
            }
        });

        vinho_Ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vinho_AnoActionPerformed(evt);
            }
        });

        vinho_Acucarado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vinho_AcucaradoActionPerformed(evt);
            }
        });

        vinho_Aroma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vinho_AromaActionPerformed(evt);
            }
        });

        vinho_Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vinho_PrecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addGap(93, 93, 93))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(vinho_Fabricante)
                                .addComponent(vinho_Ano)
                                .addComponent(vinho_Acucarado)
                                .addComponent(vinho_Aroma)
                                .addComponent(vinho_Preco)
                                .addComponent(vinho_Nome)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(adicionar_Vinho, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(vinho_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(vinho_Fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(vinho_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(vinho_Acucarado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(vinho_Aroma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(vinho_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionar_Vinho, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vinho_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinho_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vinho_NomeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Tela_Gerenciar_Vinho_Refeição a = new Tela_Gerenciar_Vinho_Refeição();
        a.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void adicionar_VinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionar_VinhoActionPerformed
    
    //Salvar informacoes dos campos no banco 
    
    
    if(vinho_Nome.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null,"Campo Nome em branco!");
            return;
        }
    if(vinho_Fabricante.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null,"Campo Fabricante em branco!");
            return;
        }
     if(vinho_Ano.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null,"Campo Ano em branco!");
            return;
        }
     if(vinho_Acucarado.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null,"Campo Açucarado em branco!");
            return;
        }
    if(vinho_Aroma.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null,"Campo Aroma em branco!");
            return;
        }
     if(vinho_Preco.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null,"Campo Preço em branco!");
            return;
        }
    Vinho vinheto = new Vinho(vinho_Nome.getText(),
                              vinho_Fabricante.getText(),
                              vinho_Ano.getText(),
                              vinho_Acucarado.getText(),
                              vinho_Aroma.getText(),
                              vinho_Preco.getText());
        //System.out.println(vinho_Nome.getText());
        VinhoDao aux = new VinhoDao();
        List<Vinho> vinhos = new ArrayList<>();
                      
        vinhos = aux.getVinhos();
        
        for (Vinho vin : vinhos) {
            
            if(vin.getNome().equals(vinho_Nome.getText()))
            {
                JOptionPane.showMessageDialog(null,"Vinho já cadastrado!");
                return;
                
            }
        }
        
        
    VinhoDao vin = new VinhoDao();
    vin.adicionaVinho(vinheto);
    // se OK...
    JOptionPane.showMessageDialog(null,"Vinho cadastrado com sucesso!");
    dispose();
    Tela_Gerenciar_Vinho_Refeição a = new Tela_Gerenciar_Vinho_Refeição();
    a.setVisible(true);
    }//GEN-LAST:event_adicionar_VinhoActionPerformed

    private void vinho_FabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinho_FabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vinho_FabricanteActionPerformed

    private void vinho_AnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinho_AnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vinho_AnoActionPerformed

    private void vinho_AcucaradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinho_AcucaradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vinho_AcucaradoActionPerformed

    private void vinho_AromaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinho_AromaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vinho_AromaActionPerformed

    private void vinho_PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinho_PrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vinho_PrecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Adicionar_Vinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Adicionar_Vinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Adicionar_Vinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Adicionar_Vinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Adicionar_Vinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar_Vinho;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField vinho_Acucarado;
    private javax.swing.JTextField vinho_Ano;
    private javax.swing.JTextField vinho_Aroma;
    private javax.swing.JTextField vinho_Fabricante;
    private javax.swing.JTextField vinho_Nome;
    private javax.swing.JTextField vinho_Preco;
    // End of variables declaration//GEN-END:variables
}
